http:
  middlewares:
    add_trace_test:
      plugin:
        traceIdHeader:
          addToResponse: true
  routers:
    test:
      rule: "PathPrefix(`/`)"
      middlewares:
        - add_trace_test
      service: api@internal
